name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          auto-update-conda: true

      - name: set quiet and append channels
        run: conda config --append channels conda-forge

      - name: install requirements
        run: conda install --file requirements-dev.txt --quiet --yes

      - name: install the package
        run: python -m pip install .

      - name: run the tests and
        run: pytest dbexample/tests --showlocals

      - name: check code style
        run: flake8

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
