name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.3
        with:
          activate-conda: true
          update-conda: false

      - name: set quiet and append channels
        run: conda config --append channels conda-forge

      - name: install requirements
        run: conda install --file requirements-dev.txt --quiet --yes

      - name: install the package
        run: python -m pip install .

      - name: run the tests and
        run: pytest dbexample/tests --showlocals

      - name: check code style
        run: flake8

      - name: deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/build/html # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
